import Head from "next/head";
import {
  Box,
  Button,
  Input,
  Text,
  ChakraProvider,
  Center,
  Image,
} from "@chakra-ui/react";
import { useState } from "react";

export default function Home() {
  const [searchQuery, setSearchQuery] = useState("");
  const [searchData, setSearchData] = useState(null);
  const [searchError, setSearchError] = useState("");

  const handleSpotifyLogin = () => {
    window.location.href = "/api/getSpotifyToken";
  };

  const handleSearch = async () => {
    const accessToken =
   
    "BQBQjn-I1rcqXLUgNBHVxst3DqopsR205h5SouaB12TRrCjgrlgOcctBlWi4rwLWQ3BQI6pqlm-nYJtbn2eb83z8HnW75ynTZ8TsGRbEU3FYziYjkKX4mBrFnrI9EqxRzWlaywC-HemOJU_02XlN1mw6bhu6HI8utqB870qfcY5oAs9eIw2qt-7-3Q6UanjnqYHGvjVwYizE_AYi4Zayvjz4ugejeCs2nq17P5BnA1ybEE9jaifydzclWxwghyIVBU-22OCcFtX_1A"

    const apiUrl = "https://api.spotify.com/v1/search";

    const queryParams = new URLSearchParams({
      q: searchQuery,
      type: "album",
      market: "BR",
    });
  
    const requestOptions = {
      method: "GET",
      headers: {
        Authorization: `Bearer ${accessToken}`,
      },
    };

    const finalUrl = `${apiUrl}?${queryParams.toString()}`;

    try {
      const response = await fetch(finalUrl, requestOptions);
      const data = await response.json();

      console.log("Dados da resposta:", data);
      setSearchData(data);
    } catch (error) {
      console.error("Erro na requisição:", error);
      setSearchError("Erro ao realizar a pesquisa.");
    }
  };

  return (
    <>
      <Head>
        <title>Alegria</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <ChakraProvider>
        <Center>
          <Box as="main">
            <Box className="description" />

            <Box className="grid">
              <Center>
                <Button onClick={handleSpotifyLogin} className="card">
                  Entrar na Alegria
                </Button>
              </Center>
              <Box className="searchForm">
                <Input
                  type="text"
                  placeholder="Digite sua pesquisa"
                  value={searchQuery}
                  onChange={(e) => setSearchQuery(e.target.value)}
                />
                <Center>
                  <Button onClick={handleSearch}>Pesquisar</Button>
                </Center>

                {searchData && searchData.albums && searchData.albums.items && (
                  <Box>
                    <Text>
                      Nome do álbum: {searchData.albums.items[0].name}
                    </Text>
                    <Text>
                      Artista: {searchData.albums.items[0].artists[0].name}
                    </Text>
                    <Image src={searchData.albums.items[0].images[0].url} />
                  </Box>
                )}
                {searchError && <Text color="red.500">{searchError}</Text>}
              </Box>
            </Box>
          </Box>
        </Center>
      </ChakraProvider>
    </>
  );
}
